### PR TITLE
refactor: change button variant for signIn and signUp for google and …

### PR DESCRIPTION
**Pull request by Lelik7777**
# Refactor Sign In and Sign Up Components

## Changes

1. Changed button variant for Google and GitHub sign-in/sign-up options
2. Updated error handling for sign-in and sign-up processes
3. Improved `handleErrorResponse` and `isValidErrorResponse` functions
4. Updated `ErrorResponse` type in `auth.types.ts`

### Button Variant Changes

- Modified the variant of Google and GitHub authentication buttons from [old variant] to [new variant] for better visual consistency and user experience.

### Error Handling Updates

- Implemented more robust error handling in sign-in and sign-up processes.
- Now catching and properly displaying specific error messages from the backend.

### handleErrorResponse and isValidErrorResponse

- Refactored `handleErrorResponse` to handle both array and string message formats.
- Added an optional `isToast` parameter to control toast notifications.
- Updated `isValidErrorResponse` to accurately check the structure of error responses.

### ErrorResponse Type Update

- Modified `ErrorResponse` type in `auth.types.ts` to accommodate both array and string formats for error messages.

## Testing

- Manually tested sign-in and sign-up flows with various error scenarios.
- Verified correct display of error messages in forms and toast notifications.

## Notes

- This refactor improves error handling and provides more flexibility in how errors are displayed to users.
- The changes to button variants enhance the visual consistency of the authentication UI.

Please review and provide feedback, especially on the error handling logic and UI changes.

### CODE REVIEW

**Review by EvgeniyaYakunina — APPROVED** [review]

**Comment by Lelik7777** [comment]
run build production

**Comment by Lelik7777** [comment]
run build production

**Comment by Lelik7777** [comment]
run build production

**Comment by Lelik7777** [comment]
run build production

**Pull request merged**
