### PR TITLE
Feature/proj 103

### PR DESCRIPTION
**Pull request by EvgeniyaYakunina**
This pull request introduces a new flow for creating, viewing, and deleting posts, enhancing the user experience and improving the overall functionality of the application.

### **Changes:**

**ImagePostModal Component:**

Added a new modal component ImagePostModal to handle the creation, viewing, and deletion of posts.
The modal has three steps: 'cropping', 'filters', and 'publication', with the option to go back and forth between steps.
Implemented a view mode to display the post's details, avatar, and image.
Added a confirmation modal before closing the creation process to prevent data loss.
Used React hooks (useState, useEffect, useRef) and custom hooks (useImagePostModal) to manage the modal's state and behavior.

**useImagePostModal Hook:**

Created a custom hook useImagePostModal to handle the form submission, image upload, and post creation logic.
Used react-hook-form with zod for form validation and error handling.
Implemented asynchronous form submission with error handling using react-query's mutation hooks (useCreatePostMutation and useUploadPostImageMutation).

**Post Component:**

Created a Post component to display the form for adding a post description and location in the 'publication' step.
Forwarded the ref prop to the form element to enable programmatic form submission.
Used react-hook-form to manage the form state and validation.

**PostList Componen**t:

Updated the PostList component to display a grid of user posts with images.
Implemented a click event handler to open the ImagePostModal in view mode when a post image is clicked.
Fetched user posts using the useGetUserPostsQuery hook.

**Acceptance Criteria:**

The new ImagePostModal component should allow users to create, view, and delete posts with an intuitive, multi-step process.
The useImagePostModal hook should handle form submission, image upload, and post creation logic seamlessly.
The Post component should display the form for adding a post description and location in the 'publication' step.
The PostList component should display a grid of user posts with images and open the ImagePostModal in view mode when a post image is clicked.

### CODE REVIEW

**Review by Lelik7777 — APPROVED** [review]

**Comment by EvgeniyaYakunina** [comment]
run build production

**Comment by Lelik7777** [comment]
run build production

**Comment by NoName-ForTeam** [comment]
run build production

**Comment by NoName-ForTeam** [comment]
run build production

**Pull request merged**
